# Generated by Django 5.2.2 on 2025-06-06 05:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('specialty', models.CharField(choices=[('general_gynecology', 'General Gynecology'), ('obstetrics_gynecology', 'Obstetrics & Gynecology'), ('fertility_specialist', 'Fertility Specialist'), ('gynecologic_oncology', 'Gynecologic Oncology'), ('maternal_fetal_medicine', 'Maternal-Fetal Medicine'), ('reproductive_endocrinology', 'Reproductive Endocrinology'), ('urogynecology', 'Urogynecology'), ('pediatric_adolescent_gynecology', 'Pediatric & Adolescent Gynecology')], max_length=50)),
                ('qualification', models.TextField()),
                ('experience_years', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('clinic_name', models.CharField(blank=True, max_length=200)),
                ('clinic_address', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=1500.0, max_digits=6)),
                ('rating', models.DecimalField(decimal_places=2, default=4.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_consultations', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('busy', 'Busy')], default='active', max_length=20)),
                ('is_available_online', models.BooleanField(default=True)),
                ('is_accepting_new_patients', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True)),
                ('languages_spoken', models.CharField(default='English, Hindi', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', '-experience_years'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('patient_name', models.CharField(blank=True, max_length=100)),
                ('patient_email', models.EmailField(blank=True, max_length=254)),
                ('patient_phone', models.CharField(blank=True, max_length=15)),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('appointment_type', models.CharField(choices=[('consultation', 'General Consultation'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('routine_checkup', 'Routine Checkup')], default='consultation', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('reason_for_visit', models.TextField(blank=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('patient_notes', models.TextField(blank=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('related_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.conversation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor')),
            ],
            options={
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='PatientQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('ai_response', models.TextField()),
                ('severity_score', models.IntegerField(choices=[(1, 'Low - General Information'), (2, 'Low-Medium'), (3, 'Medium - Some Concern'), (4, 'Medium-High'), (5, 'High - Needs Attention'), (6, 'High-Medium'), (7, 'Very High - Urgent'), (8, 'Very High-Critical'), (9, 'Critical - Immediate Care'), (10, 'Emergency - Immediate Medical Attention')], default=3)),
                ('doctor_reviewed', models.BooleanField(default=False)),
                ('doctor_response', models.TextField(blank=True)),
                ('doctor_recommendation', models.TextField(blank=True)),
                ('requires_appointment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_queries', to='doctors.doctor')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='chatbot.conversation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-severity_score', '-created_at'],
            },
        ),
    ]
