[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = false

# Follow symlink for asset mount
follow_symlink = false

[features]
# Show the prompt playground
prompt_playground = false

# Process and display HTML in messages
unsafe_allow_html = true

# Process and display mathematical expressions
latex = false

# Authorize users to upload files with messages
multi_modal = true

[UI]
# Name of the app and chatbot.
name = "AI Assistant"

# Show the readme while the thread is empty.
show_readme_as_default = true

# Description of the app and chatbot. This is used for HTML tags.
description = "AI assistant powered by multiple LLM models with intelligent response selection"

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# The default value for the expand messages settings.
default_expand_messages = false

# Hide the chain of thought details from the user in the UI.
hide_cot = false

[UI.theme.light]
    background = "#f5f8fa"
    paper = "#FFFFFF"

    [UI.theme.light.primary]
        main = "#4f46e5"
        dark = "#3730a3"
        light = "#818cf8"

[UI.theme.dark]
    background = "#1a1a1a"
    paper = "#252525"

    [UI.theme.dark.primary]
        main = "#4f46e5"
        dark = "#3730a3"
        light = "#818cf8"
